#!/bin/sh

# push
PUSH_COMMAND="push"
# force option
FORCE_PUSH="force|delete|-f"
# branch prohibiting "force push"
PROTECTED_BRANCHES="(master|develop)"

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ ${remote_ref##refs/heads/} =~ $PROTECTED_BRANCHES && $PUSH_COMMAND =~ $FORCE_PUSH ]]; then
    echo "This force-push to the ${remote_ref##refs/heads/} branch has been blocked."
    echo "Get wild and tough!"
    mpg321 ~/Music/Get_Wild.mp3 > /dev/null 2>&1 &
    exit 1
  else
    aplay ~/Music/git_push.wav > /dev/null 2>&1 &
  fi
done


