#!/usr/bin/env bash

# Author: takuzoo3868
# Last Modified: 19 Nov 2018.

trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -euo pipefail
dotfiles=$HOME/.dotfiles

# load lib script (functions)
. $dotfiles/etc/lib/header.sh


## create symbolic link
echo ""
info "Creating symbolic link..."
if [ ! -d "$HOME/.local/bin" ]; then
  mkdir -p $HOME/.local/bin
fi
symlink "$dotfiles/etc/init/deploy" "$HOME/.local/bin/deploy"
echo ""

# Bash
info "bashrc"
symlink "$dotfiles/.bashrc" "$HOME/.bashrc"
symlink "$dotfiles/.bashrc_prompt" "$HOME/.bashrc_prompt"

# fish
info "fish"
if [ ! -d "$HOME/.config/fish/functions" ]; then
  mkdir -p $HOME/.config/fish/functions
fi
symlink "$dotfiles/.config/fish/config.fish" "$HOME/.config/fish/config.fish"
symlink "$dotfiles/.config/fish/fishfile" "$HOME/.config/fish/fishfile"
for i in $dotfiles/.config/fish/functions/*.fish
do
  ln -sf $i $HOME/.config/fish/functions/
done

# Git
info "gitconfig"
symlink "$dotfiles/.config/git/.gitconfig" "$HOME/.gitconfig"
symlink "$dotfiles/.config/git/.gitignore_global" "$HOME/.gitignore_global"
symlink "$dotfiles/.config/git/.gitmessage" "$HOME/.gitmessage"
mkdir -p $HOME/.git_template/hooks

# Vim
info "vimrc"
symlink "$dotfiles/.vimrc" "$HOME/.vimrc"

# Neovim
info "neovim"
symlink "$dotfiles/.config/nvim" "$HOME/.config/nvim"

# Nyaovim
info "nyaovim"
symlink "$dotfiles/.config/nyaovim" "$HOME/.config/nyaovim"

# Tmux
info "tmux.conf"
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
symlink "$dotfiles/.config/tmux/.tmux.conf" "$HOME/.tmux.conf"
symlink "$dotfiles/.config/tmux/.tmux_local.conf" "$HOME/.tmux_local.conf"
symlink "$dotfiles/.config/tmux/bin" "$HOME/.tmux/bin"
symlink "$dotfiles/.config/tmux/work.yaml" "$HOME/.tmux/work.yaml"

# radare2
info "radare2"
symlink "$dotfiles/.radare2rc" "$HOME/.radare2rc"

# ranger
info "ranger"
if [ ! -d "$HOME/.config/ranger" ]; then
  mkdir -p $HOME/.config/ranger
fi
symlink "$dotfiles/.config/ranger/rc.conf" "$HOME/.config/ranger/rc.conf"

# weechat
info "weechat"
echo "  see install sheet. --> doc/weechat.md"

# local binary
info "binary"
echo '  export PATH="$HOME/.local/bin:$PATH'
echo '  export PATH="/opt/local/bin:/opt/local/sbin:$PATH"'
for i in $dotfiles/bin/*
do
  ln -sf $i $HOME/.local/bin/
done

echo ""
info "Installation(deploy) completed."
