" 行番号表示
set number
" タイトル表示
set title
" シンタックスハイライトの有効化
syntax on
" タブ幅の設定
set tabstop=2
" \tの幅
set shiftwidth=2
" 自動インデント
set autoindent
set smarttab
" タブをスペースに変える
set expandtab
" 対応するカッコのハイライト
set showmatch
" 貼り付けモードとの切り替え
set pastetoggle=<C-E>
" カーソルが端まで来たら次の行に飛ばす
set whichwrap=b,s,h,l,<,>,[,],~
" マッピング受付時間
set timeout
set timeoutlen=1000
" キーコード受付時間
set ttimeoutlen=100
" backspaceの有効化
set backspace=indent,eol,start
" マウスの無効化
set mouse=
" ステータスライン
set statusline=%F%=[%l/%L]
