tmux_options: -2
session_name: UEC

windows:
- window_name: main
  layout: d305,238x68,0,0{132x68,0,0[132x47,0,0,1,132x20,0,48,2],105x68,133,0[105x20,133,0,3,105x47,133,21,4]}
  panes:
    - gotop -c solarized
    - lnav
    - screenfetch
    - mpsyt pl PLBFICLTzW2LckbdM1Ri6BBfpeSPwRYzXe
- window_name: file
  layout: 2a1b,238x68,0,0[238x41,0,0,5,238x26,0,42,9]
  panes:
    - ranger
    - pane
- window_name: work
  focus: true
  layout: f026,238x68,0,0{136x68,0,0,7,101x68,137,0[101x43,137,0,8,101x24,137,44,10]}
  panes:
    - pane
    - echo "IED machine: <student ID> [at] remote.ied.inf.uec.ac.jp"
    - echo "Do your BEST. No output, No life." | octocatsay | lolcat
