session_name: work

windows:
  - window_name: "work"
    focus: true
    layout: main-vertical 
    options:
      main-pane-width: 65%
    panes:
      - shell_command: yazi
        focus: true
      - shell_command: clear
      - shell_command: clear

  - window_name: "music"
    focus: false
    panes:
      - shell_command:
          - yt pl PLBFICLTzW2LckbdM1Ri6BBfpeSPwRYzXe

  - window_name: "monitor"
    focus: false
    panes:
      - shell_command:
          - btop