name: Setup

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo build-essential

      # Error Check
      - name: Install dotfiles
        run: make deploy
        env:
          TERM: xterm
          DOTPATH: ${GITHUB_WORKSPACE}
  
  arch:
    runs-on: ubuntu-latest
    container: archlinux/base:latest
    steps:
      - uses: actions/checkout@v2

      - name: Update packages
        run: pacman -Syu --noconfirm

      - name: Install required packages
        run: pacman -S --noconfirm git sudo
      
      # Error Check
      - name: Install dotfiles
        run: make deploy
        env:
          DOTPATH: ${GITHUB_WORKSPACE}
  
  # darwin:
  #   runs-on: macos-latest

  # centos:
  #   runs-on: ubuntu-latest
  #   container: centos:latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install required packages
  #       run: yum install -y git sudo
  
  #     - name: Install dotfiles
  #       run: .bin/install.sh install
